[package]
name = "statmind"
version = "0.1.0"
edition = "2021"

[dependencies]
read-process-memory = "0.1.6"
sysinfo = "0.37.2"
anyhow = { version = "1.0.75", features = [] }
discord-rich-presence = "1.0.0"
log = "0.4.20"
env_logger = "0.11.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
process-memory = "0.5.0"
mach = "0.3.2"

[build-dependencies]
anyhow = "*"
unicode-ident = "*"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "3.5.1"
embed_plist = "1.2.2"
